import Head from 'next/head'
import Link from 'next/link'
import styles from '../styles/Home.module.scss'

export default function index() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Notes</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className={styles.heading}>We're taking notes<br/>Very seriously</h1>
      <Link href="/login"><button>Get Started</button></Link>
    </div>
  )
}
