export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR';

export const SET_USER_DATA = 'SET_USER_DATA';
export const SET_LOADER_TRUE = 'SET_LOADER_TRUE';
export const SET_LOADER_FALSE = 'SET_LOADER_FALSE';
export const USER_LOG_OUT = 'USER_LOG_OUT';
export const SET_BTN_LOADER_TRUE = 'SET_BTN_LOADER_TRUE';

export const SIGN_UP_USER = 'SIGN_UP_USER';
export const SIGN_UP_USER_SUCCESS = 'SIGN_UP_USER_SUCCESS';
export const SIGN_UP_USER_ERROR = 'SIGN_UP_USER_ERROR';
